"""Init

Revision ID: d8410e4aad9b
Revises: d296537aa8fb
Create Date: 2023-05-28 14:54:48.022066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8410e4aad9b'
down_revision = 'd296537aa8fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
